### ISSUE TITLE
How do you associate this to a model?

### ISSUE THREAD

**Issue by bryantAXS** [hiteshmodha/directive-start-rating#1]
How would you go about assigning a rating to a property of a model?

**Comment by hjmodha** [comment]
Hello @bryantAXS 

#### Controller variable

you have model called rating in your controller
`$scope.rating = 0;`

#### Assigning that to directive

`<hmrating hmupto="10" hmid="r1" hmcolor="orange" rate="rating"></hmrating>`

in directive there is attribute called `rate` - it is two way binding.

so here i have assigned rating to rate, if rate will be changed then change is assigned to rating and if rating will be changed than that change will be assigned to rate.

**Comment by bryantAXS** [comment]
Got it, thanks so much!
